version: "3.1"

services:
    db-dtmoney:
        image: postgres:alpine
        ports:
            - "5432:5432"
        container_name: db-dtmoney
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - ./data:/var/lib/postgresql/data

volumes:
    data:
